# ===============================
# SERVER CONFIGURATION
# ===============================
server.port=${PORT:8084}
spring.application.name=${SPRING_APPLICATION_NAME:lucky-draw-service}

# ===============================
# DATABASE CONFIGURATION (MariaDB)
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3309/lucky_draw_db?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# ===============================================================
# SECURITY & JWT CONFIGURATION
# ===============================================================
jwt.secret=${JWT_SECRET:ouhPBmsFWNGn1/QKWEsm/2WMB4CAt4yFGv/3qYaWD4xa5DmoBD/ACvY3oVcBZmsVLl03mVuRLJ9QsKoA3Q0osg==}

# ===============================
# HIKARI CONNECTION POOL
# ===============================
spring.datasource.hikari.maximum-pool-size=10

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG