# ===============================
# SERVER CONFIGURATION
# ===============================
server.port=8083
spring.application.name=lucky-draw-service

# ===============================
# DATABASE CONFIGURATION (MariaDB)
# ===============================
spring.datasource.url=jdbc:mariadb://localhost:3306/lucky_draw_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# ===============================
# HIKARI CONNECTION POOL
# ===============================
spring.datasource.hikari.maximum-pool-size=10

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

jwt.secret=ouhPBmsFWNGn1/QKWEsm/2WMB4CAt4yFGv/3qYaWD4xa5DmoBD/ACvY3oVcBZmsVLl03mVuRLJ9QsKoA3Q0osg==

eureka.client.service-url.defaultZone=http://localhost:8761/eureka