server:
  port: 8888
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/api/auth/**, /api/profiles/**
        - id: event-service
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/api/events/**
        - id: lucky
          uri: lb://LUCKY-DRAW-SERVICE
          predicates:
            - Path=/api/lucky/**
        - id: notification
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notify/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/