import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  VI: {
    // Header
    home: "Trang chủ",
    events: "Sự kiện",
    calendar: "Lịch sự kiện",
    home_main: "Quay về trang chủ",
    news: "Bản tin",
    login: "Đăng nhập",
    logout: "Đăng xuất",
    logout_desc: "Kết thúc phiên làm việc",
    support: "Hỗ trợ kỹ thuật",
    system_name: "Hệ thống Quản lý Sự kiện IUH",
    qr_scan: "Quét QR",
    profile: "Hồ sơ cá nhân",
    dashboard: "Bảng điều khiển",
    admin_dashboard: "Bảng điều khiển Admin",
    org_dashboard: "Bảng điều khiển BTC",
    my_events: "Sự kiện của tôi",
    admin_dashboard_title: "Bảng điều khiển hệ thống",
    personal_account: "Tài khoản cá nhân",
    system_config: "Cấu hình hệ thống",
    no_email: "Chưa cập nhật email",
    confirm_logout_title: "Đăng xuất?",
    confirm_logout_question: "Bạn có chắc chắn muốn rời khỏi hệ thống ngay bây giờ không?",
    management: "Quản lý",
    MENU: "Danh mục chính",
    SUPPORT: "Hỗ trợ",
    welcome_guest: "Chào mừng bạn",
    login_now: "Đăng nhập ngay",
    language_label: "Ngôn ngữ",
    you_have: "Bạn có",
    new_notifications_suffix: "thông báo mới",
    no_unread_notifications: "Không có thông báo mới",
    iuh_ecosystem: "Hệ sinh thái sự kiện IUH",
    explore_activities: "Khám phá hoạt động",
    event_hub_desc: "Khám phá và tham gia hàng trăm sự kiện được tổ chức tại IUH. Từ các hội thảo học thuật đến các lễ hội văn hóa sôi động.",
    no_events_match: "Không tìm thấy sự kiện phù hợp",
    try_another_keyword: "Vui lòng thử lại với từ khóa khác",
    no_news_feed: "Không có bản tin nào",
    stay_tuned_updates: "Hãy quay lại sau để cập nhật tin tức mới nhất",
    like: "Thích",
    reply: "Phản hồi",
    share: "Chia sẻ",
    views: "lượt xem",
    comments: "bình luận",
    write_comment: "Viết bình luận...",
    view_all_comments: "Xem tất cả bình luận",

    // Notifications
    notifications: "Thông báo",
    no_notifications: "Không có thông báo mới",
    mark_all_read: "Đánh dấu tất cả đã đọc",
    unread_notifications: "thông báo chưa đọc",
    all_caught_up: "Bạn đã xem hết thông báo",
    notifications_empty_desc: "Các thông báo mới về sự kiện và hệ thống sẽ xuất hiện tại đây.",
    view_all_notifications: "Xem tất cả thông báo",

    // Landing Page
    welcome: "Chào mừng đến với",
    event_iuh: "Sự Kiện IUH",
    explore_events: "Khám phá sự kiện",
    ongoing_events: "Sự Kiện đang Diễn Ra",
    upcoming_events: "Sự kiện sắp diễn ra",
    featured_events: "Sự kiện tiêu biểu",
    view_all: "Xem tất cả",
    no_ongoing: "Hiện không có sự kiện nào đang diễn ra",
    no_upcoming: "Chưa có sự kiện sắp tới",
    featured_events_subtitle: "Đừng bỏ lỡ những hoạt động hấp dẫn tại IUH",
    hero_badge: "Hệ thống quản lý sự kiện 4.0",
    hero_desc: "Nền tảng tích hợp hỗ trợ tổ chức sự kiện, điểm danh QR Code và vòng quay may mắn. Kết nối sinh viên và giảng viên trong một hệ sinh thái số hiện đại.",
    highlight: "Nổi bật",
    no_featured: "Hiện chưa có sự kiện tiêu biểu",
    features_title: "Tính Năng Nổi Bật",
    features_desc: "Hệ thống cung cấp bộ công cụ toàn diện giúp tối ưu hóa quy trình tổ chức và nâng cao trải nghiệm người tham gia.",
    ai_feature: "AI Hỗ Trợ Toàn Diện",
    ai_feature_desc: "Tự động hóa quy trình từ lập kế hoạch, viết nội dung truyền thông đến phân tích phản hồi sau sự kiện.",
    qr_feature: "Check-in QR Code",
    qr_feature_desc: "Điểm danh nhanh chóng chỉ với 1 giây. Hệ thống tự động ghi nhận thời gian và xác thực người tham gia.",
    lucky_feature: "Vòng Quay May Mắn",
    lucky_feature_desc: "Tăng tương tác với minigame vòng quay tích hợp. Tự động chọn người trúng thưởng minh bạch.",
    stat_feature: "Thống Kê Real-time",
    stat_feature_desc: "Theo dõi số lượng đăng ký, tỉ lệ tham gia và hiệu quả sự kiện qua các biểu đồ trực quan thời gian thực.",
    event_type: "Loại sự kiện",
    participants: "Người tham gia",
    details: "Chi tiết",
    ongoing: "Đang diễn ra",
    upcoming: "Sắp diễn ra",

    // Footer
    iuh_full_name: "Đại học Công nghiệp TP. Hồ Chí Minh",
    address_label: "Địa chỉ",
    phone_label: "ĐT",
    admission_label: "Tuyển sinh",
    email_label: "Email",
    branches_label: "Các cơ sở và phân hiệu",
    view_map: "Xem bản đồ",
    visit_count: "Số lượng truy cập",
    online_count: "Đang online",
    copyright: "© 2026 Đại học Công nghiệp TP.HCM - IUH",
    back_to_home: "Quay về trang chủ",

    // Campuses
    main_campus_addr: "Số 12 Nguyễn Văn Bảo, P. 4, Q. Gò Vấp, TP. Hồ Chí Minh",
    branch_nv_dung: "Nguyễn Văn Dung",
    branch_nv_dung_addr: "Số 10 Nguyễn Văn Dung, Phường An Nhơn, TP.HCM",
    branch_pv_chieu: "Phạm Văn Chiêu",
    branch_pv_chieu_addr: "Số 20 Đường số 53, Phường An Hội Tây, TP.HCM",
    branch_vhtt: "Trung tâm cung ứng dịch vụ VH-TT",
    branch_vhtt_addr: "Số 5A Nguyễn Văn Lượng, phường An Hội Đông, TP.HCM",
    branch_nhon_trach: "Nhơn Trạch",
    branch_nhon_trach_addr: "xã Phước An, tỉnh Đồng Nai",
    branch_thanh_hoa: "Thanh Hóa",
    branch_thanh_hoa_addr: "Phường Quảng Phú, tỉnh Thanh Hóa",
    branch_quang_ngai: "Phân hiệu Quảng Ngãi",
    branch_quang_ngai_addr: "Số 938 đường Quang Trung, phường Chánh Lộ, tỉnh Quảng Ngãi",

    // Login
    login_title: "Đăng nhập",
    welcome_back: "Chào mừng bạn quay trở lại!",
    username_label: "Tên đăng nhập",
    password_label: "Mật khẩu",
    username_placeholder: "Nhập tên đăng nhập",
    password_placeholder: "Nhập mật khẩu",
    remember_me: "Ghi nhớ đăng nhập",
    forgot_password: "Quên mật khẩu?",
    login_button: "Đăng nhập",
    processing: "Đang xử lý...",
    no_account: "Chưa có tài khoản?",
    register_now: "Đăng ký ngay",
    support_contact: "Liên hệ bộ phận hỗ trợ",
    back_btn: "Quay lại",
    iuh_system_title: "Hệ thống Quản lý Sự kiện IUH",
    iuh_system_desc: "Nền tảng số hóa toàn bộ quy trình tổ chức sự kiện — từ đăng ký, check-in đến thống kê và báo cáo realtime.",
    login_success: "Đăng nhập thành công! Đang chuyển hướng",
    login_error: "Tên đăng nhập hoặc mật khẩu không chính xác.",
    username_required: "Tên đăng nhập không được để trống",
    password_required: "Mật khẩu không được để trống",
    login_problem: "Gặp vấn đề khi đăng nhập?",
    trusted_by: "Hàng nghìn người dùng tin tưởng sử dụng",
    login_feat_event: "Quản lý sự kiện",
    login_feat_event_desc: "Tạo và theo dõi toàn bộ sự kiện trong trường",
    login_feat_qr: "QR Check-in",
    login_feat_qr_desc: "Điểm danh nhanh chóng bằng mã QR cá nhân",
    login_feat_users: "Quản lý người dùng",
    login_feat_users_desc: "Phân quyền linh hoạt theo vai trò",
    login_feat_stats: "Thống kê realtime",
    login_feat_stats_desc: "Báo cáo và phân tích dữ liệu tức thì",

    // Event Feed
    search_by_name: "Tìm theo tên sự kiện",
    enter_event_name: "Nhập tên sự kiện...",
    quick_access: "TRUY CẬP NHANH",
    new_notifications: "Thông báo mới",
    my_events_label: "Sự kiện của tôi",
    all_tab: "Tất cả",
    search_events_placeholder: "Tìm sự kiện...",
    reg_deadline_label: "Hạn đăng ký",
    event_schedule_title: "Lịch trình Sự kiện",
    event_schedule_subtitle: "Theo dõi và quản lý các sự kiện bạn đã tham gia",
    grid_view: "Dạng lưới",
    calendar_view: "Dạng lịch",
    loading_schedule: "Đang tải lịch trình của bạn...",
    no_events_found: "Không tìm thấy sự kiện nào",
    no_events_registered_desc: "Có vẻ như bạn chưa đăng ký tham gia sự kiện nào hoặc không tìm thấy kết quả phù hợp.",
    explore_now: "Khám phá sự kiện ngay",
    schedule_weekly_title: "Lịch sự kiện theo tuần",
    current_btn: "Hiện tại",
    prev_week: "Trở về",
    next_week: "Tiếp theo",
    shift_label: "Ca",
    shift_morning: "Sáng",
    shift_afternoon: "Chiều",
    shift_evening: "Tối",
    location_label: "Địa điểm",
    time_label: "Thời gian",
    organizer_label: "Đơn vị tổ chức",
    notes_label: "Ghi chú",
    academic_workshop: "Sự kiện Học thuật / Workshop",
    volunteer_competition: "Sự kiện Tình nguyện / Cuộc thi",
    online_webinar: "Sự kiện Trực tuyến / Webinar",
    culture_sports: "Sự kiện Văn hóa / Hội thao",
    cancelled_suspended: "Sự kiện đã hủy / Tạm ngưng",

    // Event Detail
    event_intro: "Giới thiệu sự kiện",
    target_audience: "Đối tượng tham gia",
    detailed_schedule: "Lịch trình chi tiết",
    sessions_count: "Phiên",
    presenters_guests: "Diễn giả & Khách mời",
    total_label: "Tổng cộng",
    registered_label: "Đã đăng ký",
    deadline_label: "Thời hạn",
    seats_label: "Ghế",
    cancel_reg: "Hủy đăng ký tham gia",
    survey_label: "Khảo sát",
    q_and_a_label: "Hỏi đáp",
    free_label: "Miễn phí",
    internal_event: "Sự kiện nội bộ",
    reg_redirect: "Đang chuyển hướng đến trang đăng nhập để đăng ký tham gia sự kiện!",
    reg_success: "Đăng ký thành công!",
    cancel_success: "Đã hủy đăng ký",
    reg_failed: "Đăng ký thất bại",
    checkin_success: "Điểm danh thành công!",
    invalid_qr: "Mã QR không hợp lệ",
    initializing: "Khởi tạo không gian sự kiện...",
    confirm_cancel: "Hủy đăng ký?",
    confirm_cancel_desc: "Bạn chắc chắn muốn hủy tham gia? Bạn có thể mất suất nếu sự kiện đã đủ người.",
    cancel_confirm_btn: "Hủy ngay",
    explore_more: "Tìm hiểu thêm",
    everyone_welcome: "Mọi người quan tâm",
    event_not_found: "Không tìm thấy sự kiện",
    event_date_label: "Ngày diễn ra",
    session_normal: "Phiên họp",
    checked_in_status: "Đã điểm danh ✓",
    view_ticket: "Xem vé tham gia",
    scan_checkin: "Quét mã điểm danh",
    reg_deadline_passed: "Hết hạn đăng ký",

    // Attendance
    auto_checkin: "Check-in tự động",
    scanner_desc: "Đưa mã QR của sinh viên vào khung quét. Hệ thống sẽ đối soát với danh sách đăng ký và ghi nhận điểm danh ngay lập tức.",
    ready_to_checkin: "Sẵn sàng điểm danh",
    open_camera: "Mở Camera",
    scanning_success: "THÀNH CÔNG!",
    scanning_error: "LỖI!",
    confirmed_presence: "Đã xác nhận sự hiện diện của sinh viên",
    invalid_or_used_qr: "Mã không hợp lệ hoặc đã được sử dụng trước đó.",
    scan_next: "Quét mã tiếp theo",
    try_again_btn: "THỬ LẠI",
    camera_access_error: "Không thể truy cập camera. Vui lòng kiểm tra quyền truy cập.",
    checkin_success_toast: "Điểm danh thành công!",

    // Register Modal
    login_required_title: "Yêu cầu đăng nhập",
    confirm_reg_title: "Xác nhận đăng ký",
    need_login_desc: "Bạn cần đăng nhập để tiếp tục",
    performing_reg_desc: "Bạn đang thực hiện đăng ký tham gia sự kiện",
    not_updated: "Chưa cập nhật",
    cancel_btn: "Hủy bỏ",
    confirm_now: "Xác nhận ngay",
    guest_note: "Vui lòng đăng nhập để có thể tham gia các hoạt động của sự kiện.",
    member_note: "Bằng cách nhấn xác nhận, bạn đồng ý với các điều khoản tham gia của sự kiện này.",

    // Sidebar
    overview: "Tổng quan",
    propose_plans: "Đề xuất kế hoạch",
    approve_plans: "Duyệt kế hoạch",
    manage_events: "Quản lý sự kiện",
    posts: "Bản tin & Truyền thông",
    manage_accounts: "Quản lý tài khoản",
    organization: "Cơ cấu tổ chức",
    permissions: "Phân quyền hệ thống",
    templates: "Kho mẫu sự kiện",
    games: "Trò chơi & Vòng quay",
    event_management: "Quản lý sự kiện",
    check_in: "Điểm danh QR",
    task_management: "Nhiệm vụ của tôi",

    // Calendar
    mon: "Thứ 2",
    tue: "Thứ 3",
    wed: "Thứ 4",
    thu: "Thứ 5",
    fri: "Thứ 6",
    sat: "Thứ 7",
    sun: "Chủ nhật",
    month: "Tháng",
    category_academic: "Học Thuật - Kỹ năng",
    category_culture: "Văn Hóa - Văn nghệ",
    category_sports: "Thể thao",
    category_community: "Vì Cộng Đồng",
    category_intl: "Quốc tế",
    category_festival: "Lễ hội trường",
    category_forum: "Diễn đàn - Hội thảo",
    events_on: "Sự kiện ngày",
    more_events: "sự kiện khác",
    close_btn: "Đóng",
    registered_count: "người đã đăng ký",
    program: "Chương trình",
    presenters: "Diễn giả",
    organizer_team: "Ban tổ chức",
    registrations_tab: "Đăng ký",
    attendance_tab: "Điểm danh",
    challenges: "Thử thách",
    survey: "Khảo sát",
    lucky_draw_tab: "Vòng quay may mắn",
    statistics: "Thống kê",
    ai_analysis: "Phân tích AI",
    settings: "Cài đặt",

    // Statuses
    status_draft: "Bản nháp",
    status_plan_pending: "Kế hoạch chờ duyệt",
    status_plan_approved: "Kế hoạch đã duyệt",
    status_event_pending: "Sự kiện chờ duyệt",
    status_published: "Đã công bố",
    status_ongoing: "Đang diễn ra",
    status_completed: "Đã kết thúc",
    status_cancelled: "Đã hủy",
    status_rejected: "Đã từ chối",
    status_converted: "Sự kiện đã bị hủy",
    event_timeline: "Lộ trình thời gian",
    reg_deadline_short: "Hạn đăng ký",
    start_short: "Bắt đầu",
    end_short: "Kết thúc",
    today: "HÔM NAY",
    current_time: "Hiện tại",
    your_permissions: "Quyền hạn của bạn",
    current_position: "Vị trí hiện tại",
    operation_capability: "Khả năng thao tác",
    view_as_guest: "Bạn đang xem với tư cách khách",
    general_info: "Thông tin chung",
    event_topic: "Chủ đề",
    event_type_label: "Loại sự kiện",
    max_participants_label: "Số lượng tối đa",
    target_audience_label: "Đối tượng & Đơn vị",
    target_objects: "Đối tượng mục tiêu",
    responsible_personnel: "Nhân sự phụ trách",
    event_creator_label: "Người tạo sự kiện",
    event_approver_label: "Người duyệt sự kiện",
    unlimited: "Không giới hạn",
    edit_event_perm: "Chỉnh sửa sự kiện",
    manage_team_perm: "Quản lý nhân sự",
    checkin_perm: "Thực hiện điểm danh",
    view_stats_perm: "Xem báo cáo thống kê",
    people: "người",

    // News / Posts
    news_banner_title: "Bảng tin sự kiện",
    news_banner_subtitle: "Khám phá các câu chuyện và khoảnh khắc từ sự kiện của chúng tôi",
    filter_by_event: "Lọc theo sự kiện",
    search_event_placeholder: "Tìm sự kiện...",
    all_news: "Tất cả tin tức",
    no_events_found_match: "Không tìm thấy sự kiện nào khớp",
    no_events_public_posts: "Chưa có sự kiện nào có bài viết công khai.",
    loading_news: "Đang tải bảng tin...",
    no_news_yet: "Chưa có tin tức nào",
    select_other_filter: "Vui lòng chọn bộ lọc khác hoặc quay lại sau.",
    comments_disabled: "Bình luận đã bị tắt.",
    author_label: "Tác giả",
    views_count: "lượt xem",
    reactions_count: "người tương tác",
    total_comments_count: "bình luận",
    event_label: "Sự kiện",
    copy_link_success: "Đã sao chép liên kết bài viết!",
    back: "Quay lại",
    try_again: "Thử lại",
    post_not_found: "Không tìm thấy bài viết",
    loading_post_content: "Đang tải nội dung bài viết...",
    liked_label: "Đã thích",
    react_awesome: "Tuyệt vời",
    react_happy: "Hạnh phúc",
    react_congrats: "Chúc mừng",
    react_applause: "Tán thưởng",
    react_wow: "Ngạc nhiên",
    react_sad: "Chia buồn",
    react_haha: "Haha",
    react_love: "Yêu thích",
    react_great: "Tuyệt quá",
    react_sparkle: "Lấp lánh",
    react_respect: "Trân trọng",
    react_perfect: "Tuyệt đối",
    react_useful: "Hữu ích",

    // Comment Sorting & Interaction
    sort_relevant: "Phù hợp nhất",
    sort_newest: "Mới nhất",
    sort_all: "Tất cả bình luận",
    sort_relevant_desc: "Hiển thị bình luận có nhiều lượt tương tác nhất trước tiên.",
    sort_newest_desc: "Hiển thị tất cả bình luận, mới nhất trước tiên.",
    sort_all_desc: "Hiển thị tất cả bình luận, bao gồm cả nội dung có thể là spam.",
    view_replies: "Xem {{count}} phản hồi",
    hide_replies: "Ẩn phản hồi",
    time_now: "Đăng mới đây vừa xong",
    time_min: "phút",
    time_hour: "giờ",
    time_day: "ngày",
    view_more_comments: "Xem thêm bình luận",
    delete_comment_confirm_title: "Xóa bình luận?",
    delete_comment_confirm_desc: "Bạn có chắc chắn muốn xóa bình luận này không?",
    hide_comment_confirm_title: "Ẩn bình luận?",
    hide_comment_confirm_desc: "Bình luận này sẽ bị ẩn khỏi mọi người nhưng vẫn lưu trong hệ thống.",
    delete: "Xóa",

    // Roles
    role_super_admin: "Quản trị viên cấp cao",
    role_admin: "Quản trị viên",
    role_lecturer: "Giảng viên / Tổ chức",
    role_student: "Sinh viên",
    role_member: "Thành viên",
    role_leader: "Trưởng nhóm",
    role_sub_leader: "Phó nhóm",
    role_secretary: "Thư ký",
    role_member_org: "Thành viên tổ chức",
    role_guest: "Khách",
    role_approver: "Người duyệt sự kiện",

    // Common
    loading: "Đang tải...",
    cancel: "Hủy",
    confirm_logout: "Bạn có chắc chắn muốn đăng xuất khỏi tài khoản?",
    send: "Gửi",
    load_more_comments: "Xem thêm bình luận",
  },
  EN: {
    // Header
    home: "Home",
    events: "Events",
    calendar: "Calendar",
    home_main: "Back to Home",
    news: "News",
    login: "Login",
    logout: "Logout",
    logout_desc: "End current session",
    support: "Technical Support",
    system_name: "IUH Event Management System",
    qr_scan: "Scan QR",
    profile: "Personal Profile",
    dashboard: "Dashboard",
    admin_dashboard: "Admin Dashboard",
    org_dashboard: "Organizer Dashboard",
    my_events: "My Events",
    admin_dashboard_title: "System Control Panel",
    personal_account: "Personal Account",
    system_config: "System Configuration",
    no_email: "No email updated",
    confirm_logout_title: "Logout?",
    confirm_logout_question: "Are you sure you want to leave the system now?",
    management: "Management",
    MENU: "Main Menu",
    SUPPORT: "Support",
    welcome_guest: "Welcome guest",
    login_now: "Login now",
    language_label: "Language",
    you_have: "You have",
    new_notifications_suffix: "new notifications",
    no_unread_notifications: "No new notifications",
    iuh_ecosystem: "IUH Event Ecosystem",
    explore_activities: "Explore Activities",
    event_hub_desc: "Discover and participate in hundreds of events organized by IUH. From academic seminars to vibrant cultural festivals.",
    no_events_match: "No events match your criteria",
    try_another_keyword: "Please try another keyword or filter",
    no_news_feed: "No news feed available",
    stay_tuned_updates: "Stay tuned for future updates",
    like: "Like",
    reply: "Reply",
    share: "Share",
    views: "views",
    comments: "comments",
    write_comment: "Write a comment...",
    view_all_comments: "View all comments",

    // Notifications
    notifications: "Notifications",
    no_notifications: "No new notifications",
    mark_all_read: "Mark all as read",
    unread_notifications: "unread notifications",
    all_caught_up: "You're all caught up",
    notifications_empty_desc: "New notifications about events and system will appear here.",
    view_all_notifications: "View all notifications",

    // Landing Page
    welcome: "Welcome to",
    event_iuh: "IUH Events",
    explore_events: "Explore Events",
    ongoing_events: "Ongoing Events",
    upcoming_events: "Upcoming Events",
    featured_events: "Featured Events",
    view_all: "View All",
    no_ongoing: "No events are currently ongoing",
    no_upcoming: "No upcoming events",
    featured_events_subtitle: "Don't miss out on exciting activities at IUH",
    hero_badge: "Event Management System 4.0",
    hero_desc: "An integrated platform supporting event organization, QR Code attendance, and lucky draws. Connecting students and lecturers in a modern digital ecosystem.",
    highlight: "Featured",
    no_featured: "No featured events at the moment",
    features_title: "Key Features",
    features_desc: "The system provides a comprehensive set of tools to optimize organization processes and enhance participant experience.",
    ai_feature: "Comprehensive AI Support",
    ai_feature_desc: "Automate processes from planning, media content writing to post-event feedback analysis.",
    qr_feature: "QR Code Check-in",
    qr_feature_desc: "Fast attendance in just 1 second. The system automatically records time and verifies participants.",
    lucky_feature: "Lucky Draw Spinner",
    lucky_feature_desc: "Increase interaction with integrated mini-games. Automatically select winners transparently.",
    stat_feature: "Real-time Statistics",
    stat_feature_desc: "Track registration numbers, participation rates, and event effectiveness via real-time intuitive charts.",
    event_type: "Event Type",
    participants: "Participants",
    details: "Details",
    ongoing: "Ongoing",
    upcoming: "Upcoming",

    // Footer
    iuh_full_name: "Industrial University of Ho Chi Minh City",
    address_label: "Address",
    phone_label: "Tel",
    admission_label: "Admission",
    email_label: "Email",
    branches_label: "Campuses & Branches",
    view_map: "View Map",
    visit_count: "Total Visits",
    online_count: "Online",
    copyright: "© 2026 Industrial University of Ho Chi Minh City - IUH",
    back_to_home: "Back to home",

    // Campuses
    main_campus_addr: "12 Nguyen Van Bao, Ward 4, Go Vap District, Ho Chi Minh City",
    branch_nv_dung: "Nguyen Van Dung Campus",
    branch_nv_dung_addr: "10 Nguyen Van Dung, An Nhon Ward, HCMC",
    branch_pv_chieu: "Pham Van Chieu Campus",
    branch_pv_chieu_addr: "20 Street 53, An Hoi Tay Ward, HCMC",
    branch_vhtt: "VH-TT Service Center",
    branch_vhtt_addr: "5A Nguyen Van Luong, An Hoi Dong Ward, HCMC",
    branch_nhon_trach: "Nhon Trach Campus",
    branch_nhon_trach_addr: "Phuoc An Village, Dong Nai Province",
    branch_thanh_hoa: "Thanh Hoa Campus",
    branch_thanh_hoa_addr: "Quang Phu Ward, Thanh Hoa Province",
    branch_quang_ngai: "Quang Ngai Branch",
    branch_quang_ngai_addr: "938 Quang Trung Street, Chanh Lo Ward, Quang Ngai Province",

    // Login
    login_title: "Login",
    welcome_back: "Welcome back!",
    username_label: "Username",
    password_label: "Password",
    username_placeholder: "Enter your username",
    password_placeholder: "Enter your password",
    remember_me: "Remember me",
    forgot_password: "Forgot password?",
    login_button: "Login",
    processing: "Processing...",
    no_account: "Don't have an account?",
    register_now: "Register now",
    support_contact: "Contact support",
    back_btn: "Back",
    iuh_system_title: "IUH Event Management System",
    iuh_system_desc: "A digital platform automating the entire event process — from registration and check-in to real-time statistics and reporting.",
    login_success: "Login successful! Redirecting",
    login_error: "Invalid username or password.",
    username_required: "Username is required",
    password_required: "Password is required",
    login_problem: "Having trouble logging in?",
    trusted_by: "Trusted by thousands of users",
    login_feat_event: "Event Management",
    login_feat_event_desc: "Create and track all events within the university",
    login_feat_qr: "QR Check-in",
    login_feat_qr_desc: "Fast attendance using personal QR codes",
    login_feat_users: "User Management",
    login_feat_users_desc: "Flexible role-based access control",
    login_feat_stats: "Real-time Statistics",
    login_feat_stats_desc: "Instant data reporting and analysis",

    // Event Feed
    search_by_name: "Search by event name",
    enter_event_name: "Enter event name...",
    quick_access: "QUICK ACCESS",
    new_notifications: "New notifications",
    my_events_label: "My events",
    all_tab: "All",
    search_events_placeholder: "Search events...",
    reg_deadline_label: "Registration deadline",
    event_schedule_title: "Event Schedule",
    event_schedule_subtitle: "Track and manage the events you've participated in",
    grid_view: "Grid View",
    calendar_view: "Calendar View",
    loading_schedule: "Loading your schedule...",
    no_events_found: "No events found",
    no_events_registered_desc: "It seems you haven't registered for any events yet or no matching results were found.",
    explore_now: "Explore events now",
    schedule_weekly_title: "Weekly Event Schedule",
    current_btn: "Today",
    prev_week: "Previous",
    next_week: "Next",
    shift_label: "Shift",
    shift_morning: "Morning",
    shift_afternoon: "Afternoon",
    shift_evening: "Evening",
    location_label: "Location",
    time_label: "Time",
    organizer_label: "Organizer",
    notes_label: "Notes",
    academic_workshop: "Academic / Workshop",
    volunteer_competition: "Volunteer / Competition",
    online_webinar: "Online / Webinar",
    culture_sports: "Culture / Sports",
    cancelled_suspended: "Cancelled / Suspended",

    // Event Detail
    event_intro: "Event Introduction",
    target_audience: "Target Audience",
    detailed_schedule: "Detailed Schedule",
    sessions_count: "Sessions",
    presenters_guests: "Presenters & Guests",
    total_label: "Total",
    registered_label: "Registered",
    deadline_label: "Deadline",
    seats_label: "Seats",
    cancel_reg: "Cancel Registration",
    survey_label: "Survey",
    q_and_a_label: "Q&A",
    free_label: "Free",
    internal_event: "Internal Event",
    reg_redirect: "Redirecting to login to register for this event!",
    reg_success: "Registration successful!",
    cancel_success: "Registration cancelled",
    reg_failed: "Registration failed",
    checkin_success: "Check-in successful!",
    invalid_qr: "Invalid QR code",
    initializing: "Initializing event space...",
    confirm_cancel: "Cancel Registration?",
    confirm_cancel_desc: "Are you sure you want to cancel? You might lose your spot if the event fills up.",
    cancel_confirm_btn: "Cancel Now",
    explore_more: "Explore More",
    everyone_welcome: "Everyone interested",
    event_not_found: "Event not found",
    event_date_label: "Event Date",
    session_normal: "Session",
    checked_in_status: "Checked-in ✓",
    view_ticket: "View Ticket",
    scan_checkin: "Scan Check-in",
    reg_deadline_passed: "Registration deadline passed",

    // Attendance
    auto_checkin: "Automatic Check-in",
    scanner_desc: "Place the student's QR code in the scanning frame. The system will match it with the registration list and record attendance instantly.",
    ready_to_checkin: "Ready to Check-in",
    open_camera: "Open Camera",
    scanning_success: "SUCCESS!",
    scanning_error: "ERROR!",
    confirmed_presence: "Student presence confirmed",
    invalid_or_used_qr: "Invalid code or already used.",
    scan_next: "Scan next code",
    try_again_btn: "TRY AGAIN",
    camera_access_error: "Cannot access camera. Please check permissions.",
    checkin_success_toast: "Check-in successful!",

    // Register Modal
    login_required_title: "Login Required",
    confirm_reg_title: "Confirm Registration",
    need_login_desc: "You need to login to continue",
    performing_reg_desc: "You are registering for this event",
    not_updated: "Not updated",
    cancel_btn: "Cancel",
    confirm_now: "Confirm Now",
    guest_note: "Please login to participate in event activities.",
    member_note: "By confirming, you agree to the event's terms and conditions.",

    // Sidebar
    overview: "Overview",
    propose_plans: "Propose Plans",
    approve_plans: "Approve Plans",
    manage_events: "Manage Events",
    posts: "Media Posts",
    manage_accounts: "Manage Accounts",
    organization: "Organization",
    permissions: "System Permissions",
    templates: "Event Templates",
    games: "Games & Spinner",
    event_management: "Event Management",
    check_in: "QR Check-in",
    task_management: "My Tasks",

    // Calendar
    mon: "Mon",
    tue: "Tue",
    wed: "Wed",
    thu: "Thu",
    fri: "Fri",
    sat: "Sat",
    sun: "Sun",
    month: "Month",
    category_academic: "Academic - Skills",
    category_culture: "Culture - Arts",
    category_sports: "Sports",
    category_community: "Community",
    category_intl: "International",
    category_festival: "University Festival",
    category_forum: "Forum - Seminar",
    events_on: "Events on",
    more_events: "more events",
    close_btn: "Close",
    registered_count: "registered",
    program: "Program",
    presenters: "Presenters",
    organizer_team: "Organizer Team",
    registrations_tab: "Registrations",
    attendance_tab: "Attendance",
    challenges: "Challenges",
    survey: "Survey",
    lucky_draw_tab: "Lucky Draw",
    statistics: "Statistics",
    ai_analysis: "AI Analysis",
    settings: "Settings",

    // Statuses
    status_draft: "Draft",
    status_plan_pending: "Plan Pending",
    status_plan_approved: "Plan Approved",
    status_event_pending: "Event Pending",
    status_published: "Published",
    status_ongoing: "Ongoing",
    status_completed: "Completed",
    status_cancelled: "Cancelled",
    status_rejected: "Rejected",
    status_converted: "Event Cancelled",
    event_timeline: "Event Timeline",
    reg_deadline_short: "Reg Deadline",
    start_short: "Start",
    end_short: "End",
    today: "TODAY",
    current_time: "Now",
    your_permissions: "Your Permissions",
    current_position: "Current Position",
    operation_capability: "Capabilities",
    view_as_guest: "You are viewing as guest",
    general_info: "General Info",
    event_topic: "Topic",
    event_type_label: "Event Type",
    max_participants_label: "Max Participants",
    target_audience_label: "Audience & Units",
    target_objects: "Target Audience",
    responsible_personnel: "Responsible Personnel",
    event_creator_label: "Event Creator",
    event_approver_label: "Event Approver",
    unlimited: "Unlimited",
    edit_event_perm: "Edit Event",
    manage_team_perm: "Manage Team",
    checkin_perm: "Perform Check-in",
    view_stats_perm: "View Statistics",
    people: "people",

    // News / Posts
    news_banner_title: "Event Bulletin",
    news_banner_subtitle: "Explore stories and moments from our events",
    filter_by_event: "Filter by event",
    search_event_placeholder: "Search events...",
    all_news: "All news",
    no_events_found_match: "No matching events found",
    no_events_public_posts: "No events have public posts yet.",
    loading_news: "Loading news feed...",
    no_news_yet: "No news articles yet",
    select_other_filter: "Please select another filter or come back later.",
    comments_disabled: "Comments are disabled.",
    author_label: "Author",
    views_count: "views",
    reactions_count: "interactions",
    total_comments_count: "comments",
    event_label: "Event",
    copy_link_success: "Post link copied!",
    back: "Back",
    try_again: "Try again",
    post_not_found: "Post not found",
    loading_post_content: "Loading post content...",
    liked_label: "Liked",
    react_awesome: "Awesome",
    react_happy: "Happy",
    react_congrats: "Congrats",
    react_applause: "Applause",
    react_wow: "Wow",
    react_sad: "Sad",
    react_haha: "Haha",
    react_love: "Love",
    react_great: "Great",
    react_sparkle: "Sparkle",
    react_respect: "Respect",
    react_perfect: "Perfect",
    react_useful: "Useful",

    // Comment Sorting & Interaction
    sort_relevant: "Most Relevant",
    sort_newest: "Newest",
    sort_all: "All Comments",
    sort_relevant_desc: "Show comments with the most interactions first.",
    sort_newest_desc: "Show all comments, newest first.",
    sort_all_desc: "Show all comments, including potential spam.",
    view_replies: "View {{count}} replies",
    hide_replies: "Hide replies",
    time_now: "Just now",
    time_min: "m",
    time_hour: "h",
    time_day: "d",
    view_more_comments: "View more comments",
    delete_comment_confirm_title: "Delete Comment?",
    delete_comment_confirm_desc: "Are you sure you want to delete this comment?",
    hide_comment_confirm_title: "Hide Comment?",
    hide_comment_confirm_desc: "This comment will be hidden from the public but kept in our records.",
    delete: "Delete",

    // Roles
    role_super_admin: "Super Admin",
    role_admin: "Administrator",
    role_lecturer: "Lecturer / Organizer",
    role_student: "Student",
    role_member: "Member",
    role_leader: "Team Leader",
    role_sub_leader: "Sub-leader",
    role_secretary: "Secretary",
    role_member_org: "Org Member",
    role_guest: "Guest",
    role_approver: "Event Approver",

    // Common
    loading: "Loading...",
    cancel: "Cancel",
    confirm_logout: "Are you sure you want to log out?",
    send: "Send",
    load_more_comments: "Load more comments",
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const stored = localStorage.getItem('app-language') || 'VI';
    return stored.toUpperCase();
  });

  useEffect(() => {
    localStorage.setItem('app-language', language.toUpperCase());
  }, [language]);

  const t = (key) => {
    const langKey = (language || 'VI').toUpperCase();
    const dict = translations[langKey] || translations['VI'];
    return dict[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
