# ===============================
# SERVER CONFIGURATION
# ===============================
server.port=8081
spring.application.name=event-service

# ===============================
# DATABASE CONFIGURATION (MariaDB)
# ===============================
spring.datasource.url=jdbc:mariadb://mariadb:3306/event_db
spring.datasource.username=root
spring.datasource.password=sapassword
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# ===============================
# HIKARI CONNECTION POOL
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.jackson.deserialization.fail-on-null-for-primitives=false

spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.web=DEBUG

eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka