# ===============================================================
# SERVER & APPLICATION CONFIGURATION
# ===============================================================
server.port=${PORT}
spring.application.name=${SPRING_APPLICATION_NAME}

# ===============================================================
# DATABASE CONFIGURATION (MariaDB)
# ===============================================================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.datasource.hikari.maximum-pool-size=10

# ===============================================================
# JPA / HIBERNATE CONFIGURATION
# ===============================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

spring.jackson.deserialization.fail-on-null-for-primitives=false

# ===============================================================
# SECURITY & JWT CONFIGURATION
# ===============================================================
jwt.secret=${JWT_SECRET}

# ===============================================================
# KAFKA CONFIGURATION
# ===============================================================
spring.kafka.producer.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

logging.level.org.apache.kafka=DEBUG
logging.level.org.springframework.kafka=DEBUG

# ================== EMAIL CONFIGURATION ==================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hiennguyenbuitan@gmail.com
spring.mail.password=xaillzeygjsxjqss
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# ===============================================================
# REDIS CONFIGURATION
# ===============================================================
spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT}

# ===============================================================
# LOGGING CONFIGURATION
# ===============================================================
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG

spring.jackson.serialization.fail-on-empty-beans=false
